version: "3"
services:
  frontend:
    container_name: weather_front
    build: ./frontend
    image: weather_front:2.0
    ports:
      - "8000:8000"
    volumes:
      - ./frontend/src:/usr/src/app/src
  backend:
    container_name: weather_back
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: weather_back
    ports:
      - "9000:9000"
    volumes:
      - ./backend/src:/usr/src/app/src
