version: "3"
services:
  frontend:
    container_name: weather_front
    build: ./frontend
    image: weather-app-front:2.1
    ports:
      - "8000:8000"
    volumes:
      - ./frontend/src:/usr/src/app/src
  backend:
    container_name: weather_back
    build: ./backend
    image: weather-app-back:2.1
    ports:
      - "9000:9000"
    volumes:
      - ./backend/src:/usr/src/app/src
